[[listen]]
protocol = "vlesss"
uuid = "a684455c-b14f-11ea-bf0d-42010aaa0003"
host = "0.0.0.0"
port = 4434
version = 0
insecure = true
fallback = ":80"
cert = "cert.pem"
key = "cert.key"
advancedLayer = "ws"
path = "/ohmygod_verysimple_is_very_simple"
extra = { ws_earlydata = true }

[[dial]]
protocol = "direct"

