[[listen]]
protocol = "vlesss"
uuid = "a684455c-b14f-11ea-bf0d-42010aaa0003"
host = "0.0.0.0"
port = 4434
version = 0
insecure = true
fallback = ":1010"    #在grpcSimple时（即默认情况下），本作的grpc也是支持回落的！要回落到 h2c
cert = "cert.pem"
key = "cert.key"
advancedLayer = "grpc"
path = "ohmygod_verysimple_is_very_simple"  #正常来说不宜前面再加斜杠,不过加了斜杠也能用(两端都加的情况下), 因为只是个字符串, 所以无所谓

# 如需使用 Nginx、Caddy 等软件进行分流，设置的分流路径应为 /${path}/Tun
#   比如当前示例的情况下，Nginx的配置就是 /ohmygod_verysimple_is_very_simple/Tun

[[dial]]
protocol = "direct"

