[[listen]]
protocol = "vlesss"
uuid = "a684455c-b14f-11ea-bf0d-42010aaa0003"
host = "0.0.0.0"
port = 4434
insecure = true
#fallback = ":1010"    #在grpcSimple时（即默认情况下），本作的grpc也是支持回落的！要回落到 h2c, 就是说这里 你 1010端口 要用 nginx 监听 h2c
cert = "cert.pem"
key = "cert.key"
advancedLayer = "grpc"
path = "ohmygod_verysimple_is_very_simple"  #前面加斜杠了话, 程序会自动把斜杠移除

# 这个path填的就是 v2ray中的 "service name", 因为 service name 在技术实现上就是url的path的一部分而已.

# 如需使用 Nginx、Caddy 等软件进行分流，其设置的分流路径应为 /${path}/Tun
#   比如当前示例的情况下，Nginx的配置就是 /ohmygod_verysimple_is_very_simple/Tun

tag = "vless-grpc-tls-in"

[[dial]]
protocol = "direct"


[[fallback]]    # grpcSimple 回落到nginx的 grpc h2c
from = ["vless-grpc-tls-in"]
alpn = ["h2"]
dest = "127.0.0.1:80"

#dest = "/home/me/shm.sock" # 回落到unix domain socket
