[[listen]]
protocol = "socks5"			 
host = "127.0.0.1"
port = 10800

[[dial]]
protocol = "trojans"
tag = "t"
host = "cloud.tecent.com"
ip = "127.0.0.1"    #这里为了本机测试, 设成了127.0.0.1 , 你改成你vps的ip.
port = 4433
uuid = "a684455c-b14f-11ea-bf0d-42010aaa0003"
tls_type = "shadowTls2"
#extra = { tls_minVersion = "1.2",tls_maxVersion = "1.2" }   # 用于 shadowTls v1
extra = { shadowtls_password = "a684455c-b14f-11ea-bf0d-42010aaa0003"}  # 用于 shadowTls v2

# vs的 shadowTls v2中，自动使用了 uTls，使用了chrome指纹,无需配置. 强强联合, 更爽.


# [dns]
# listen = "udp://127.0.0.1:8053"
# servers = [
# 	"udp://114.114.114.114:53",
# ]

# [dns.hosts]
# "cloud.tecent.com" = "127.0.0.1"

# 上面的dns模块用于在本机测试 shadowTls 功能. 将你的电脑的dns指向listen的地址, 然后在浏览器中输入 cloud.tecent.com, 
# 应该能正常回落

# 不过如果使用了这个dns，则你不能在本机同时开 server和client，否则 server想向外拨 cloud.tecent.com 时就又回环到自己了。
