[[listen]]
protocol = "socks5"
host = "127.0.0.1"
port = 10800


[[dial]]
protocol = "trojans"
uuid = "a684455c-b14f-11ea-bf0d-42010aaa0003"
host = "127.0.0.1"
port = 4434
insecure = true
tls_type = "utls"
advancedLayer = "grpc"
path = "ohmygod_verysimple_is_very_simple"
use_mux = true

# 只是一种奇葩组合而已，为了证明 确实可以 trojan + grpc +smux +simplesocks
# quic也是可以的. 过于奇葩，对应的服务端配置就不给出了。
