[[listen]]
protocol = "trojans"
uuid = "a684455c-b14f-11ea-bf0d-42010aaa0003"
ip = "0.0.0.0"
host = "your-domain-name.com"
port = 4434
insecure = true
fallback = ":80"
cert = "cert.pem"
key = "cert.key"
#advancedLayer = "ws"
#path = "/ohmygod_verysimple_is_very_simple"
#early = true 

[[dial]]
protocol = "direct"
# fullcone = true # 默认的fullcone是关闭状态, 可以取消注释以打开. trojan的udp是可以做到fullcone的.