# this is a verysimple standard server config
[[listen]]
tag = "my_vlesss1"
protocol = "vlesss"
#uuid = "a684455c-b14f-11ea-bf0d-42010aaa0003"   # uuid 只能填一个用户, 如果你有多个用户, 可用 users. 
# uuid 和 users 这两个配置可以共存。
users = [ {user = "a684455c-b14f-11ea-bf0d-42010aaa0003"} ]

host = "0.0.0.0"
port = 4433
#version = 0     # 在服务端，如果version给出，则只 支持 监听特定版本的vless, 若请求版本不符合，将拒绝连接(或者回落).
insecure = true
fallback = ":80"    
# 默认回落地址.ip必须是本机ip(可以省略ip而只写端口,程序会默认补全127.0.0.1),
# 或者unix domain socket的文件名/路径, 或者 udp://127.0.0.1:80 这种url格式。

# （用udp以试图回落到 nginx的 无tls 的 udp的 http3 服务端口，适用于 quic的情况. 只能由其它协议回落到quic, 而不能由 quic 回落到quic, 没办法, 依赖的代码包不够强大.）

cert = "cert.pem"   # 这里既可以默认放在程序本身目录下，也可以指定完整路径
key = "cert.key"    # 如果 cert和key中 有一项没给出, 或者文件不存在, 就会自动在内存中生成随机证书,

# 我们作为示例, 就直接随机证书了, 不提供现成的证书。这样可以 避免很多小白 共同使用相同的证书 导致被 审查者 察觉.

#xver = 1   

# 可选, 高级用法, 小白不用管. 若为1或者2, 则监听 PROXY protocol, 用于nginx等回落到 verysimple 
# 注意，这和fallback项中的 xver意义正好相反. 
# 实际上目前无论给出的是1还是2, 都会同时监听 v1和v2. 不过这只是目前代码的实现而已, 也许未来会改动, 所以你还是确定选用一个版本.

# ca = "ca.crt" # 可选, 用于验证客户端证书

#lazy = true

# extra = { tls_minVersion = "1.2" }    # 默认的 minVersion 是1.3，你还可以设成1.2，其它值无效。

# fullcone = true # 只有当listen和dial在 client和server配置 均为 fullcone时, 才会真正fullcone生效

[[dial]]
protocol = "direct"
# fullcone = true   # 默认的fullcone是关闭状态, 可以取消注释以打开. 不过vless v0的话没用，因为vless v0不支持fullcone。 v1或者trojan可以打开 该选项.

# fallback这一项是可选的，如果没有的话，或者未匹配，则默认使用listen提供的fallback
# 如果listen也没提供fallback，那就会直接断开连接
[[fallback]]
dest = 6060     # 必填, 这里的意思是 回落到本机端口 6060, 格式和上方的 默认回落地址 的格式相同。

# 如果一个 fallback 只给出了 dest，那么它就和 listen里的 fallback 等价。当然，如果有多个listen的话就不等价了，此时可用 from 指出 fallback用于哪一个 server，详见 multi.server.toml
# 如果不用 from进行区分，那么 这种 fallback 会适用于 所有 listen的回落，即作为 终极默认回落

# 还可以用 dest = "@my_vlesss1" 这种方式 来匹配 某个 tag的 listen 的 地址，好处就是不用重复写地址了

# path = "/asf"   # 可选，按path 匹配此 回落

# dest = "127.0.0.1:8080"  # dest 还可以用这种格式
# dest = "/path/to/your/unix_domain_socket"    # 还可以用 unix domain socket 的文件名,可以绝对路径或者相对路径

# 还可以按sni和 alpn匹配（tls里的host和 alpn）

# sni = "your.domain.com"
# alpn = ["h2","http/1.1"]

# 一个fallback中 可以多个条件同时匹配，此时只有完全匹配所有条件 才算匹配 此fallback

# 另外，sni和alpn的 匹配 只在 我们listen配置使用了 tls时才会有效，比如如果nginx前置的话，那么我们就是无法匹配这两项的.

#xver = 1   

# 可选， 用于 回落到nginx 等情况时 传递客户端原始地址。
# 如果为1，则表示 使用 PROXY protocol version 1, 如果为 2, 则表示 PROXY protocol version 2, 其他值无效。

[[fallback]]
dest = 80 
path = "/asf"
